2021-08-18 14:27:55,097 (72194/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-08-18 14:27:55,125 (72194/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  role "george" does not exist\n\n'
2021-08-18 14:28:31,859 (72295/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-08-18 14:29:39,844 (72295/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * FROM public.product | less', error: SyntaxError('syntax error at or near "|"\nLINE 1: SELECT * FROM public.product | less\n                                     ^\n')
2021-08-18 14:29:39,845 (72295/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "|"\nLINE 1: SELECT * FROM public.product | less\n                                     ^\n\n'
2022-06-08 10:27:15,960 (4031/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-06-08 10:27:19,154 (4031/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/run/postgresql/.s.PGSQL.5432"?\n\n'
2022-06-08 10:27:58,273 (5899/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-06-08 10:27:58,373 (5899/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/run/postgresql/.s.PGSQL.5432"?\n\n'
2022-06-08 10:28:37,978 (6197/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-06-08 10:28:41,546 (6197/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not translate host name "ost" to address: Name or service not known\n\n'
