2021-08-18 14:27:55,097 (72194/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-08-18 14:27:55,125 (72194/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  role "george" does not exist\n\n'
2021-08-18 14:28:31,859 (72295/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2021-08-18 14:29:39,844 (72295/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * FROM public.product | less', error: SyntaxError('syntax error at or near "|"\nLINE 1: SELECT * FROM public.product | less\n                                     ^\n')
2021-08-18 14:29:39,845 (72295/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "|"\nLINE 1: SELECT * FROM public.product | less\n                                     ^\n\n'
2022-06-08 10:27:15,960 (4031/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-06-08 10:27:19,154 (4031/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/run/postgresql/.s.PGSQL.5432"?\n\n'
2022-06-08 10:27:58,273 (5899/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-06-08 10:27:58,373 (5899/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/run/postgresql/.s.PGSQL.5432"?\n\n'
2022-06-08 10:28:37,978 (6197/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-06-08 10:28:41,546 (6197/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not translate host name "ost" to address: Name or service not known\n\n'
2022-06-14 12:30:49,406 (15307/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-06-14 12:30:49,555 (15307/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/run/postgresql/.s.PGSQL.5432"?\n\n'
2022-06-14 12:31:13,614 (15397/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-06-14 12:31:17,321 (15397/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not translate host name "localhost:5432" to address: Name or service not known\n\n'
2022-06-14 12:31:40,425 (15471/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-06-14 12:31:44,318 (15471/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not translate host name "localhost:54321" to address: Name or service not known\n\n'
2022-06-14 12:31:56,052 (15511/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-06-14 12:32:02,770 (15536/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-06-14 12:32:02,860 (15536/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: Connection refused\n\tIs the server running on host "localhost" (::1) and accepting\n\tTCP/IP connections on port 54321?\ncould not connect to server: Connection refused\n\tIs the server running on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 54321?\n\n'
2022-06-14 12:32:05,728 (15567/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-06-14 12:32:58,379 (15567/MainThread) pgcli.pgexecute ERROR - sql: 'tables', error: SyntaxError('syntax error at or near "tables"\nLINE 1: tables\n        ^\n')
2022-06-14 12:32:58,379 (15567/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "tables"\nLINE 1: tables\n        ^\n\n'
2022-06-14 12:33:28,738 (15567/MainThread) pgcli.pgexecute ERROR - sql: '/h', error: SyntaxError('syntax error at or near "/"\nLINE 1: /h\n        ^\n')
2022-06-14 12:33:28,739 (15567/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "/"\nLINE 1: /h\n        ^\n\n'
2022-06-14 12:33:30,168 (15567/MainThread) pgcli.pgexecute ERROR - sql: 'help', error: SyntaxError('syntax error at or near "help"\nLINE 1: help\n        ^\n')
2022-06-14 12:33:30,168 (15567/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "help"\nLINE 1: help\n        ^\n\n'
2022-06-14 12:35:18,102 (16624/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-06-14 12:35:21,790 (16624/MainThread) pgcli.pgexecute ERROR - sql: '\\t', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\t\n        ^\n')
2022-06-14 12:35:21,790 (16624/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\t\n        ^\n\n'
2022-06-14 12:37:55,336 (17502/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-06-14 12:41:11,340 (19554/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-07-06 16:07:47,121 (2325/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-07-06 16:07:47,243 (2325/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: Connection refused\n\tIs the server running on host "localhost" (::1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Connection refused\n\tIs the server running on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\n\n'
2022-07-06 16:19:11,306 (9915/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-07-06 16:19:35,013 (9915/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * FROM public.product | less LIMIT 2', error: SyntaxError('syntax error at or near "|"\nLINE 1: SELECT * FROM public.product | less LIMIT 2\n                                     ^\n')
2022-07-06 16:19:35,014 (9915/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "|"\nLINE 1: SELECT * FROM public.product | less LIMIT 2\n                                     ^\n\n'
2022-07-12 12:06:57,041 (25450/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-07-12 12:08:28,789 (25450/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT id from reaction >>', error: SyntaxError('syntax error at or near ">>"\nLINE 1: SELECT id from reaction >>\n                                ^\n')
2022-07-12 12:08:28,789 (25450/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near ">>"\nLINE 1: SELECT id from reaction >>\n                                ^\n\n'
2022-07-27 15:52:35,738 (37332/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-07-28 10:34:39,150 (7417/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-07-28 10:34:45,898 (7417/MainThread) pgcli.pgexecute ERROR - sql: 'sele', error: SyntaxError('syntax error at or near "sele"\nLINE 1: sele\n        ^\n')
2022-07-28 10:34:45,899 (7417/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "sele"\nLINE 1: sele\n        ^\n\n'
2022-09-06 11:38:55,496 (21279/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-09-06 11:39:52,998 (21279/MainThread) pgcli.pgexecute ERROR - sql: 'select * from design where user_id="ol3clo.fzcmpy2"', error: UndefinedColumn('column "ol3clo.fzcmpy2" does not exist\nLINE 1: select * from design where user_id="ol3clo.fzcmpy2"\n                                           ^\n')
2022-09-06 11:39:52,999 (21279/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedColumn: column "ol3clo.fzcmpy2" does not exist\nLINE 1: select * from design where user_id="ol3clo.fzcmpy2"\n                                           ^\n\n'
2022-09-21 12:14:44,659 (12299/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-09-21 12:14:44,795 (12299/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 640, in connect\n    raise e\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n  File "/usr/lib/python3.10/site-packages/psycopg/connection.py", line 725, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: Connection refused\n\tIs the server running on host "localhost" (::1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Connection refused\n\tIs the server running on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\n'
2022-09-21 12:15:06,544 (13171/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-09-21 12:15:06,619 (13171/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 640, in connect\n    raise e\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n  File "/usr/lib/python3.10/site-packages/psycopg/connection.py", line 725, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: Connection refused\n\tIs the server running on host "localhost" (::1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Connection refused\n\tIs the server running on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\n'
2022-09-21 12:15:39,598 (13735/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-09-21 12:15:39,672 (13735/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 640, in connect\n    raise e\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n  File "/usr/lib/python3.10/site-packages/psycopg/connection.py", line 725, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: Connection refused\n\tIs the server running on host "localhost" (::1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Connection refused\n\tIs the server running on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\n'
2022-09-21 12:16:18,420 (13816/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-09-21 12:16:18,496 (13816/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 640, in connect\n    raise e\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n  File "/usr/lib/python3.10/site-packages/psycopg/connection.py", line 725, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: Connection refused\n\tIs the server running on host "localhost" (::1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Connection refused\n\tIs the server running on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\n'
2022-09-21 12:17:09,930 (13885/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-09-21 12:17:27,453 (14295/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-09-21 12:17:51,785 (14295/MainThread) pgcli.pgexecute ERROR - sql: 'select * from pla', error: UndefinedTable('relation "pla" does not exist\nLINE 1: select * from pla\n                      ^')
2022-09-21 12:17:51,786 (14295/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: relation "pla" does not exist\nLINE 1: select * from pla\n                      ^\n'
2022-09-21 12:22:24,608 (19292/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-10-04 10:54:53,515 (19396/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-10-04 10:54:54,779 (19396/MainThread) pgcli.pgexecute ERROR - sql: 'sele', error: SyntaxError('syntax error at or near "sele"\nLINE 1: sele\n        ^')
2022-10-04 10:54:54,779 (19396/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "sele"\nLINE 1: sele\n        ^\n'
2022-10-04 11:56:54,102 (12758/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-10-19 17:50:39,115 (68913/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-10-19 17:51:08,341 (68913/MainThread) pgcli.pgexecute ERROR - sql: 'select slug from shop_config where slug like "test%"', error: UndefinedColumn('column "test%" does not exist\nLINE 1: select slug from shop_config where slug like "test%"\n                                                     ^')
2022-10-19 17:51:08,341 (68913/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "test%" does not exist\nLINE 1: select slug from shop_config where slug like "test%"\n                                                     ^\n'
2022-10-19 18:00:18,247 (68913/MainThread) pgcli.pgexecute ERROR - sql: "select slug from shop_config where slug like 'test-%01' or slug ='test' order", error: SyntaxError("syntax error at end of input\nLINE 1: ...shop_config where slug like 'test-%01' or slug ='test' order\n                                                                       ^")
2022-10-19 18:00:18,248 (68913/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at end of input\nLINE 1: ...shop_config where slug like \'test-%01\' or slug =\'test\' order\n                                                                       ^\n'
2022-11-29 11:07:01,395 (17001/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-11-29 11:07:06,226 (17001/MainThread) pgcli.pgexecute ERROR - sql: 'ls', error: SyntaxError('syntax error at or near "ls"\nLINE 1: ls\n        ^')
2022-11-29 11:07:06,227 (17001/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "ls"\nLINE 1: ls\n        ^\n'
2022-12-07 11:48:16,711 (170320/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-12-07 11:48:23,265 (170320/MainThread) pgcli.pgexecute ERROR - sql: 'select * from', error: SyntaxError('syntax error at end of input\nLINE 1: select * from\n                     ^')
2022-12-07 11:48:23,266 (170320/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at end of input\nLINE 1: select * from\n                     ^\n'
2022-12-07 14:13:09,032 (193925/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-12-07 15:26:25,716 (223582/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-12-08 10:55:56,532 (18261/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-12-08 10:55:56,682 (18261/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 640, in connect\n    raise e\n  File "/usr/lib/python3.10/site-packages/pgcli/main.py", line 627, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 161, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 207, in connect\n    conn = psycopg.connect(conn_info)\n  File "/usr/lib/python3.10/site-packages/psycopg/connection.py", line 727, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: Connection refused\n\tIs the server running on host "localhost" (::1) and accepting\n\tTCP/IP connections on port 54321?\ncould not connect to server: Connection refused\n\tIs the server running on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 54321?\n'
2022-12-08 10:56:25,425 (18555/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-12-08 10:56:28,713 (18555/MainThread) pgcli.pgexecute ERROR - sql: 'se', error: SyntaxError('syntax error at or near "se"\nLINE 1: se\n        ^')
2022-12-08 10:56:28,714 (18555/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "se"\nLINE 1: se\n        ^\n'
2022-12-08 10:56:35,612 (18555/MainThread) pgcli.pgexecute ERROR - sql: 'select * from ete', error: UndefinedTable('relation "ete" does not exist\nLINE 1: select * from ete\n                      ^')
2022-12-08 10:56:35,612 (18555/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 725, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: relation "ete" does not exist\nLINE 1: select * from ete\n                      ^\n'
2022-12-13 10:39:14,533 (22621/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-12-13 13:11:25,778 (35828/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-12-13 14:57:06,981 (209625/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-01-03 13:28:53,262 (16077/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-01-03 13:29:02,793 (16077/MainThread) pgcli.pgexecute ERROR - sql: 'select * from plat', error: UndefinedTable('relation "plat" does not exist\nLINE 1: select * from plat\n                      ^')
2023-01-03 13:29:02,794 (16077/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 728, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: relation "plat" does not exist\nLINE 1: select * from plat\n                      ^\n'
2023-01-09 20:40:32,782 (27357/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-01-10 15:23:04,517 (57253/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-01-10 15:28:16,851 (57253/MainThread) pgcli.pgexecute ERROR - sql: 'selec * from user_platform_product', error: SyntaxError('syntax error at or near "selec"\nLINE 1: selec * from user_platform_product\n        ^')
2023-01-10 15:28:16,852 (57253/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 728, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "selec"\nLINE 1: selec * from user_platform_product\n        ^\n'
2023-01-10 16:05:24,222 (78918/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-01-10 16:07:13,145 (79892/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-01-12 16:16:20,599 (237749/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-01-12 16:16:23,605 (237749/MainThread) pgcli.pgexecute ERROR - sql: 'sel', error: SyntaxError('syntax error at or near "sel"\nLINE 1: sel\n        ^')
2023-01-12 16:16:23,606 (237749/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 728, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "sel"\nLINE 1: sel\n        ^\n'
2023-01-12 16:24:37,106 (237749/MainThread) pgcli.pgexecute ERROR - sql: 'select username,name,status from user_platform_product join eternia_user ON eternia_user.id = user_platform_product.user_id', error: UndefinedColumn('column "name" does not exist\nLINE 1: select username,name,status from user_platform_product join ...\n                        ^')
2023-01-12 16:24:37,106 (237749/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 728, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "name" does not exist\nLINE 1: select username,name,status from user_platform_product join ...\n                        ^\n'
2023-01-12 16:25:22,400 (237749/MainThread) pgcli.pgexecute ERROR - sql: 'select username,name,status from user_platform_product join eternia_user ON eternia_user.id = user_platform_product.user_id where eternia_user.username="wudynyw"', error: UndefinedColumn('column "name" does not exist\nLINE 1: select username,name,status from user_platform_product join ...\n                        ^')
2023-01-12 16:25:22,400 (237749/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 728, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "name" does not exist\nLINE 1: select username,name,status from user_platform_product join ...\n                        ^\n'
2023-01-12 16:25:27,870 (237749/MainThread) pgcli.pgexecute ERROR - sql: 'select username,status from user_platform_product join eternia_user ON eternia_user.id = user_platform_product.user_id where eternia_user.username="wudynyw"', error: UndefinedColumn('column "wudynyw" does not exist\nLINE 1: ...atform_product.user_id where eternia_user.username="wudynyw"\n                                                              ^')
2023-01-12 16:25:27,870 (237749/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 728, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "wudynyw" does not exist\nLINE 1: ...atform_product.user_id where eternia_user.username="wudynyw"\n                                                              ^\n'
2023-01-12 16:25:47,013 (237749/MainThread) pgcli.pgexecute ERROR - sql: 'select username,name,status from user_platform_product join eternia_user ON eternia_user.id = user_platform_product.user_id', error: UndefinedColumn('column "name" does not exist\nLINE 1: select username,name,status from user_platform_product join ...\n                        ^')
2023-01-12 16:25:47,013 (237749/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 728, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "name" does not exist\nLINE 1: select username,name,status from user_platform_product join ...\n                        ^\n'
2023-01-12 16:35:43,762 (249844/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-01-12 16:43:59,967 (255114/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-01-13 15:29:34,776 (59189/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-01-13 15:29:38,154 (59189/MainThread) pgcli.pgexecute ERROR - sql: 'select * from eter', error: UndefinedTable('relation "eter" does not exist\nLINE 1: select * from eter\n                      ^')
2023-01-13 15:29:38,154 (59189/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 728, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: relation "eter" does not exist\nLINE 1: select * from eter\n                      ^\n'
2023-01-13 15:30:30,800 (59189/MainThread) pgcli.pgexecute ERROR - sql: 'select username,_parent_email from eternia_user where username = fixov', error: UndefinedColumn('column "fixov" does not exist\nLINE 1: ...rname,_parent_email from eternia_user where username = fixov\n                                                                  ^')
2023-01-13 15:30:30,800 (59189/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 728, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "fixov" does not exist\nLINE 1: ...rname,_parent_email from eternia_user where username = fixov\n                                                                  ^\n'
2023-01-13 15:40:11,933 (64348/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-01-13 16:31:04,303 (79718/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-01-26 15:02:14,931 (35362/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-02-01 15:56:29,523 (55529/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-02-01 15:56:56,658 (55529/MainThread) pgcli.pgexecute ERROR - sql: 'select * from shop_config where slug"nazibehaz"', error: SyntaxError('syntax error at or near ""nazibehaz""\nLINE 1: select * from shop_config where slug"nazibehaz"\n                                            ^')
2023-02-01 15:56:56,659 (55529/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near ""nazibehaz""\nLINE 1: select * from shop_config where slug"nazibehaz"\n                                            ^\n'
2023-03-09 13:44:10,326 (71458/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-03-09 15:24:27,562 (84788/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-03-14 12:14:54,589 (33667/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-03-30 11:37:27,349 (19376/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-04-03 10:07:00,634 (3163/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-04-03 10:39:55,141 (9965/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-04-04 10:54:57,457 (7814/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-04-04 11:10:03,666 (15559/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-04-04 11:14:52,829 (17715/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-04-24 11:38:02,029 (12691/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-03 11:17:53,391 (34308/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-03 11:17:59,924 (34308/MainThread) pgcli.pgexecute ERROR - sql: 'exit!', error: SyntaxError('syntax error at or near "exit"\nLINE 1: exit!\n        ^')
2023-05-03 11:17:59,924 (34308/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "exit"\nLINE 1: exit!\n        ^\n'
2023-05-03 11:19:41,165 (35451/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-03 11:21:42,084 (35451/MainThread) pgcli.pgexecute ERROR - sql: 'select creator_payout', error: UndefinedColumn('column "creator_payout" does not exist\nLINE 1: select creator_payout\n               ^')
2023-05-03 11:21:42,084 (35451/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "creator_payout" does not exist\nLINE 1: select creator_payout\n               ^\n'
2023-05-03 11:21:51,192 (35451/MainThread) pgcli.pgexecute ERROR - sql: 'select creator_payout from invoice_sku', error: UndefinedColumn('column "creator_payout" does not exist\nLINE 1: select creator_payout from invoice_sku\n               ^\nHINT:  Perhaps you meant to reference the column "invoice_sku.creator_payout_id".')
2023-05-03 11:21:51,192 (35451/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "creator_payout" does not exist\nLINE 1: select creator_payout from invoice_sku\n               ^\nHINT:  Perhaps you meant to reference the column "invoice_sku.creator_payout_id".\n'
2023-05-03 11:21:59,488 (35451/MainThread) pgcli.pgexecute ERROR - sql: 'select id from invoice_sku', error: UndefinedColumn('column "id" does not exist\nLINE 1: select id from invoice_sku\n               ^')
2023-05-03 11:21:59,488 (35451/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "id" does not exist\nLINE 1: select id from invoice_sku\n               ^\n'
2023-05-03 11:22:52,917 (35451/MainThread) pgcli.pgexecute ERROR - sql: 'select * from payout invoice_sku', error: UndefinedTable('relation "payout" does not exist\nLINE 1: select * from payout invoice_sku\n                      ^')
2023-05-03 11:22:52,917 (35451/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: relation "payout" does not exist\nLINE 1: select * from payout invoice_sku\n                      ^\n'
2023-05-03 12:32:59,869 (54011/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-03 12:33:27,232 (54011/MainThread) pgcli.pgexecute ERROR - sql: 'delete from product_specification', error: ForeignKeyViolation('update or delete on table "product_specification" violates foreign key constraint "fk_product_product_specification_id_product_specification" on table "product"\nDETAIL:  Key (id)=(061f0a06-7afc-11ed-9060-0242ac160005) is still referenced from table "product".')
2023-05-03 12:33:27,233 (54011/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.10/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.ForeignKeyViolation: update or delete on table "product_specification" violates foreign key constraint "fk_product_product_specification_id_product_specification" on table "product"\nDETAIL:  Key (id)=(061f0a06-7afc-11ed-9060-0242ac160005) is still referenced from table "product".\n'
2023-05-04 10:36:22,198 (27901/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-04 10:36:52,827 (27901/MainThread) pgcli.pgexecute ERROR - sql: 'exit()', error: SyntaxError('syntax error at or near "exit"\nLINE 1: exit()\n        ^')
2023-05-04 10:36:52,829 (27901/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "exit"\nLINE 1: exit()\n        ^\n'
2023-05-04 11:11:11,087 (42819/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-04 11:47:17,046 (42819/MainThread) pgcli.pgexecute ERROR - sql: "INSERT INTO organization (name) VALUES('testorg1')", error: NotNullViolation('null value in column "id" violates not-null constraint\nDETAIL:  Failing row contains (null, testorg1, 2023-05-04 15:47:17.045897, 2023-05-04 15:47:17.045897).')
2023-05-04 11:47:17,046 (42819/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.NotNullViolation: null value in column "id" violates not-null constraint\nDETAIL:  Failing row contains (null, testorg1, 2023-05-04 15:47:17.045897, 2023-05-04 15:47:17.045897).\n'
2023-05-04 11:47:34,717 (42819/MainThread) pgcli.pgexecute ERROR - sql: 'exit!', error: SyntaxError('syntax error at or near "exit"\nLINE 1: exit!\n        ^')
2023-05-04 11:47:34,717 (42819/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "exit"\nLINE 1: exit!\n        ^\n'
2023-05-04 11:53:58,911 (46797/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-04 11:54:08,016 (46797/MainThread) pgcli.pgexecute ERROR - sql: "INSERT INTO organization (id,name) VALUES('123','testorg1')", error: InvalidTextRepresentation('invalid input syntax for type uuid: "123"\nLINE 1: INSERT INTO organization (id,name) VALUES(\'123\',\'testorg1\')\n                                                  ^')
2023-05-04 11:54:08,017 (46797/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.InvalidTextRepresentation: invalid input syntax for type uuid: "123"\nLINE 1: INSERT INTO organization (id,name) VALUES(\'123\',\'testorg1\')\n                                                  ^\n'
2023-05-04 11:54:22,775 (46797/MainThread) pgcli.pgexecute ERROR - sql: 'INSERT INTO organization (id,name) VALUES("123","testorg1")', error: UndefinedColumn('column "123" does not exist\nLINE 1: INSERT INTO organization (id,name) VALUES("123","testorg1")\n                                                  ^')
2023-05-04 11:54:22,776 (46797/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "123" does not exist\nLINE 1: INSERT INTO organization (id,name) VALUES("123","testorg1")\n                                                  ^\n'
2023-05-04 11:54:56,641 (46797/MainThread) pgcli.pgexecute ERROR - sql: "INSERT INTO organization (name) VALUES('testorg1')", error: NotNullViolation('null value in column "id" violates not-null constraint\nDETAIL:  Failing row contains (null, testorg1, 2023-05-04 15:54:56.640581, 2023-05-04 15:54:56.640581).')
2023-05-04 11:54:56,642 (46797/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.NotNullViolation: null value in column "id" violates not-null constraint\nDETAIL:  Failing row contains (null, testorg1, 2023-05-04 15:54:56.640581, 2023-05-04 15:54:56.640581).\n'
2023-05-04 12:11:24,657 (46797/MainThread) pgcli.pgexecute ERROR - sql: 'SEL', error: SyntaxError('syntax error at or near "SEL"\nLINE 1: SEL\n        ^')
2023-05-04 12:11:24,658 (46797/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "SEL"\nLINE 1: SEL\n        ^\n'
2023-05-08 16:05:42,026 (20888/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-08 16:05:46,551 (20888/MainThread) pgcli.pgexecute ERROR - sql: 'select * from perm', error: UndefinedTable('relation "perm" does not exist\nLINE 1: select * from perm\n                      ^')
2023-05-08 16:05:46,552 (20888/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: relation "perm" does not exist\nLINE 1: select * from perm\n                      ^\n'
2023-05-08 16:08:53,252 (22729/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-08 16:19:03,675 (22729/MainThread) pgcli.pgexecute ERROR - sql: 'select * from perm', error: UndefinedTable('relation "perm" does not exist\nLINE 1: select * from perm\n                      ^')
2023-05-08 16:19:03,675 (22729/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: relation "perm" does not exist\nLINE 1: select * from perm\n                      ^\n'
2023-05-08 16:24:07,425 (28854/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-09 10:39:57,919 (62480/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-17 14:32:34,136 (75643/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-17 14:33:48,155 (75643/MainThread) pgcli.pgexecute ERROR - sql: 'exit()', error: SyntaxError('syntax error at or near "exit"\nLINE 1: exit()\n        ^')
2023-05-17 14:33:48,156 (75643/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "exit"\nLINE 1: exit()\n        ^\n'
2023-05-17 14:34:24,127 (76157/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-05-17 14:34:48,452 (76157/MainThread) pgcli.pgexecute ERROR - sql: 'TRUNCATE * CASCADE', error: SyntaxError('syntax error at or near "*"\nLINE 1: TRUNCATE * CASCADE\n                 ^')
2023-05-17 14:34:48,453 (76157/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "*"\nLINE 1: TRUNCATE * CASCADE\n                 ^\n'
2023-05-17 14:35:11,909 (76157/MainThread) pgcli.pgexecute ERROR - sql: 'ext', error: SyntaxError('syntax error at or near "ext"\nLINE 1: ext\n        ^')
2023-05-17 14:35:11,910 (76157/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "ext"\nLINE 1: ext\n        ^\n'
2023-06-14 12:10:05,459 (25386/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-06-14 12:10:31,970 (25931/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-06-14 12:30:10,224 (42544/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-06-14 16:03:07,636 (93258/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-06-15 11:57:12,908 (26820/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-06-22 15:45:47,742 (46870/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-06-22 15:48:54,204 (46870/MainThread) pgcli.pgexecute ERROR - sql: 'select program_id from producty', error: UndefinedTable('relation "producty" does not exist\nLINE 1: select program_id from producty\n                               ^')
2023-06-22 15:48:54,205 (46870/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: relation "producty" does not exist\nLINE 1: select program_id from producty\n                               ^\n'
2023-06-22 15:56:26,640 (51710/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-06-22 16:39:16,321 (65523/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-06-22 16:42:33,538 (69193/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-06-22 16:42:54,815 (69193/MainThread) pgcli.pgexecute ERROR - sql: 'select * from profram', error: UndefinedTable('relation "profram" does not exist\nLINE 1: select * from profram\n                      ^')
2023-06-22 16:42:54,816 (69193/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 373, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 423, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 69, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: relation "profram" does not exist\nLINE 1: select * from profram\n                      ^\n'
2023-06-26 12:42:15,236 (24913/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-06-27 10:33:37,545 (11175/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2023-07-03 14:53:16,458 (41248/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
